#!/usr/bin/env sh

ACTION_NAME=${1:-custom-action-name}
APPLICATION_CLASS=${2:-my.app.Application}

HUMIO_SERVER_TOKEN=${HUMIO_SERVER_TOKEN:-"HUMIO_SERVER_TOKEN"}
HUMIO_HOSTNAME=${HUMIO_HOSTNAME:-"${ACTION_NAME}-ibm-wsk"}

ACTION_FILE=${ACTION_FILE:-../target/${ACTION_NAME}-wsk.jar}
ACTION_MAIN=${ACTION_MAIN:-com.github.chaudhryfaisal.wsk.Main}
ACTION_TYPE=${ACTION_TYPE:-update}
ACTION_PARAMS=${ACTION_PARAMS:-"-p 'HUMIO_SERVER_TOKEN' '$HUMIO_SERVER_TOKEN' -p 'HUMIO_HOSTNAME' '$HUMIO_HOSTNAME'"}

WSK=${WSK:-ibmcloud wsk}

echo "ACTION_NAME=$ACTION_NAME"
echo "ACTION_FILE=$ACTION_FILE"
echo "ACTION_MAIN=$ACTION_MAIN"
echo "APPLICATION_CLASS=$APPLICATION_CLASS"
echo "ACTION_PARAMS=$ACTION_PARAMS"
